site_name: napari-game-of-life
site_description: An n-dimensional implementation of Conway's Game of Life in napari.
site_author: Lorenzo Gaifas

theme: readthedocs


repo_url: https://github.com/brisvag/napari-game-of-life

pages:
- Home: index.md
